//PACKAGE ORG.TEST.UTIL;
//
//IMPORT JAVA.TIME.LOCALDATE;
//IMPORT JAVA.UTIL.CALENDAR;
//IMPORT JAVA.UTIL.LIST;
//IMPORT JAVA.UTIL.TIMEZONE;
//IMPORT ORG.OPENQA.SELENIUM.WEBELEMENT;
//
//PUBLIC CLASS DATEUTIL {
//    //GET THE CURRENT DAY
//    PUBLIC STATIC STRING GETCURRENTDAY() {
//        //CREATE A CALENDAR OBJECT
//        CALENDAR CALENDAR = CALENDAR.GETINSTANCE(TIMEZONE.GETDEFAULT());
//
//        //GET CURRENT DAY AS A NUMBER
//        INT TODAYINT = CALENDAR.GET(CALENDAR.DAY_OF_MONTH);
//        SYSTEM.OUT.PRINTLN("TODAY INT: " + TODAYINT + "\N");
//
//        //INTEGER TO STRING CONVERSION
//        STRING TODAYSTR = INTEGER.TOSTRING(TODAYINT);
//        SYSTEM.OUT.PRINTLN("TODAY STR: " + TODAYSTR + "\N");
//
//        RETURN TODAYSTR;
//    }
//
//    //GET THE CURRENT DAY PLUS DAYS. YOU CAN CHANGE THIS METHOD BASED ON YOUR NEEDS.
//    PUBLIC STATIC STRING GETCURRENTDAYPLUS(INT DAYS) {
//        LOCALDATE CURRENTDATE = LOCALDATE.NOW();
//
//        INT DAYOFWEEKPLUS = CURRENTDATE.GETDAYOFWEEK().PLUS(DAYS).GETVALUE();
//        RETURN INTEGER.TOSTRING(DAYOFWEEKPLUS);
//    }
//
//    //CLICK TO GIVEN DAY
//    PUBLIC STATIC VOID CLICKGIVENDAY(LIST<WEBELEMENT> ELEMENTLIST, STRING DAY) {
//        //DATEPICKER IS A TABLE. THUS WE CAN NAVIGATE TO EACH CELL
//        //AND IF A CELL MATCHES WITH THE CURRENT DATE THEN WE WILL CLICK IT.
//        /**FUNCTIONAL JAVA VERSION OF THIS METHOD.*/
//        ELEMENTLIST.STREAM()
//            .FILTER(ELEMENT -> ELEMENT.GETTEXT().CONTAINS(DAY))
//            .FINDFIRST()
//            .IFPRESENT(WEBELEMENT::CLICK);
//
//        /**NON-FUNCTIONAL JAVA VERSION OF THIS METHOD.*/
//        //FOR (
//        //    WEBELEMENT CELL : ELEMENTLIST) {
//        //    STRING CELLTEXT = CELL.GETTEXT();
//        //    IF (CELLTEXT.CONTAINS(DAY)) {
//        //        CELL.CLICK();
//        //        BREAK;
//        //    }
//        //}
//    }
//}